name: Build and push docker image

on:
  push:
    tags: [ v*.*.* ]

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Docker - authenticate
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - build and push images
        if: startsWith(github.ref, 'refs/tags')
        run: make build_image_and_push image_host=${{ env.IMAGE_HOST_SLASH_APPENDED }} image_tag=${{ steps.get_tag_version.outputs.TAG }}